hooks:
  post-checkout:
    cmd: |
      if ! command -v npm >/dev/null 2>&1; then
        curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
        sudo apt-get install -y nodejs
      fi
      cd gh-watcher && npm install
jobs:
  gh-poll:
    run:                      # standard Run-schema block
      cmd: cd gh-watcher && npm run watch                  
    schedule: "*/5 * * * *"      # crontab — every 5 minutes
    # disable_on_start: true   # uncomment if you want it created but *not* auto-scheduled